# Generated by Django 4.2.9 on 2025-11-10 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='switch',
            name='brand',
            field=models.CharField(default='Cisco', max_length=50),
        ),
        migrations.AddField(
            model_name='switch',
            name='encrypted_password',
            field=models.TextField(default='DEFAULT_ENCRYPTED_PASS'),
        ),
        migrations.AddField(
            model_name='switch',
            name='ssh_username',
            field=models.CharField(default='admin', max_length=100),
        ),
    ]
