# Generated by Django 4.2.9 on 2025-11-10 20:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tablas', '0002_switch_brand_switch_encrypted_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('SUCCESS', 'Éxito'), ('FAILED', 'Fallido'), ('RUNNING', 'En ejecución')], default='RUNNING', max_length=10)),
                ('log_output', models.TextField(blank=True, null=True)),
                ('switch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='tablas.switch')),
            ],
        ),
    ]
