# Generated by Django 4.2.9 on 2025-11-10 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablas', '0003_cleanlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cleanlog',
            options={'get_latest_by': 'timestamp', 'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='cleanlog',
            name='message_shown',
            field=models.BooleanField(default=False),
        ),
    ]
