# Generated by Django 4.2.9 on 2025-11-11 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tablas', '0004_alter_cleanlog_options_cleanlog_message_shown'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleanlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clean_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='switch',
            name='ssh_username',
            field=models.CharField(max_length=100),
        ),
    ]
